##spring.datasource.url= jdbc:mysql://localhost:3306/login
##spring.datasource.username=amrit
##spring.datasource.password=root
##spring.jpa.hibernate.ddl-auto=create-drop
##spring.appllication.name=track
##spring.cloud.config.uri=http://localhost:8888
#
#
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#fetch-registry=true
#management.security.enabled=false
#register-with-eureka=true